### ISSUE TITLE
Second Attendance move falls back to 08.00 in certain scenarios

### ISSUE THREAD

**Issue by mjoxy** [adfinis/timed-frontend#904] opened 2023-04-14 06:53 UTC
When you create a second attendance slot and you move it to start 11.30 or later (normally after lunch), it jumps back to the beginning of the day. When you move it to start before 11.30, then it saves and afterwards you can move it wherever you want.

**Comment by derrabauke** [comment] 2023-04-14 07:30
Thanks for opening the issue. :heart:  But this is a duplicate of #902 and is already fixed.

**Closed by derrabauke** 2023-04-14 07:30 UTC
