### ISSUE TITLE
"Needs review" and "Not billable" icons are not accessible

### ISSUE THREAD

**Issue by JohnL17** [adfinis/timed-frontend#887] opened 2023-03-24 16:18 UTC
I see the difference between whether an entry is marked as "needs review" or "not billable" poorly to not at all. I'm sure this is partly due to my color blindness, but the accessibility could be better. A shading or a frame would possibly help.

**Comment by derrabauke** [comment] 2023-03-24 16:43
Closing this since it's a duplicate of #858

**Closed by derrabauke** 2023-03-24 16:43 UTC
Labels: enhancement

**Comment by JohnL17** [comment] 2023-03-27 05:57
Whoops didn't see that such an issue exists already. Sorry for the noise. :sweat_smile:
